name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  lab-build:
    name: JupyterLab Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '18.x'

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install jupyter_packaging jupyterlab hatch

    - name: Install the extension
      run: |
        python -m pip install .

    - name: Check the extensions are installed
      run: |
        jupyter labextension list
        # jupyter labextension list 2>&1 | grep -ie "@voila-dashboards/jupyterlab-gridstack.*enabled.*ok" -
        # python -m jupyterlab.browser_check

    - name: Lint
      run: |
        jlpm
        jlpm run eslint:check
        jlpm run prettier:check

    - name: Test
      run: |
        jlpm && jlpm build
        jlpm run test

    - name: Build the extension
      run: |
        python -m hatch build

    - uses: actions/upload-artifact@v3
      with:
        name: gridstack-package
        path: dist/*.whl

  classic-notebook:
    name: Notebook v6 Build
    needs: lab-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        name: gridstack-package
        path: dist

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install "notebook<7"

    - name: Install the extension
      run: |
        pip install dist/*.whl

    - name: Check the extensions are installed
      run: |
        jupyter nbextension list 2>&1 | grep -ie "voila-gridstack/extension.*enabled" -
