name: UI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: '*'

jobs:
  ui-tests:
    name: Visual Regression
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter_packaging jupyterlab

      - name: Install the extension
        run: |
          python -m pip install ".[test]"
          jlpm run build
          jlpm run develop
          jupyter labextension list
          cd ui-tests
          jlpm install

      - name: Install browser
        run: npx playwright install chromium
        working-directory: ui-tests

      - name: Test
        run: jlpm run test
        working-directory: ui-tests

      - name: Upload Playwright Test assets
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: gridstack-test-assets
          path: |
            ui-tests/test-results